# Generated by Django 4.1 on 2022-08-18 10:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newpolls', '0002_betting_img'),
    ]

    operations = [
        migrations.RenameField(
            model_name='betting',
            old_name='img',
            new_name='Upload_Image',
        ),
    ]
